### ISSUE TITLE
Remove the need to manally setup DC/OS cli environment.

### ISSUE THREAD

**Issue by julienstroheker** [rgardler/acs-cli#71] opened 2016-09-08 15:18 UTC
Just a little detail / question : 

When I run
```
acs service create
```
After few minutes my acs cluster is created and I can see the installation of the dcos cli but is it normal that we have to run this last following command manually ?
```
source /src/bin/env-setup && dcos help
```

Why it is not included during the creation process of the cluster ?

**Comment by rgardler** [comment] 2016-09-08 15:55
It is normal, but only in the sense that I haven't figured out how to run that command and still affect the environment in which subsequent commands will be run. The problem is that Python does not appear to allow a subprocess (which is used to execute the relevant shell commands) to alter the environment of the parent process. I'd be happy to be corrected on that.

However, you only need to run this once if you run the container using either ./scripts/run-docker.sh or ./scripts/dev-docker.sh since these scripts will reconnect to earlier instances of the container in which you already ran the environment set (this works for azure login credentials too). The difference between the two commands is that the dev-docker.sh script mounts the source code for a faster development loop.

**Comment by julienstroheker** [comment] 2016-09-08 19:30
Thanks for your answer

**Comment by rgardler** [comment] 2016-09-11 23:18
I've been thinking about this and I think we can remove this requirement by having the dcos.execute method run the env configuration. It runs very quickly so I don't think this will be much of a performance issue. It would still be necessary to run the setup manually if the user wanted to use DCOS CLI separately, but I think this approach will remove this need if only the ACS CLI is used.

I'm reopening and marking as an "enhancement" with a new title.

**Comment by rgardler** [comment] 2016-09-18 06:43
This change seems to be working well. It is now only necessary to run the env config if you want to run dcos outside of the acs cli.

**Closed by rgardler** 2016-09-18 06:43 UTC
Labels: enhancement
